common:
  clusterDomain: ""
backend:
  name: cbomkit
  image: ghcr.io/cbomkit/cbomkit
  tag: latest
frontend:
  name: cbomkit-frontend
  image: ghcr.io/cbomkit/cbomkit-frontend
  tag: latest
opa:
    name: cbomkit-opa
    image: openpolicyagent/opa
    tag: latest
postgresql:
  fullnameOverride: cbomkit-postgres
  postgresql:
  image:
    repository: bitnamilegacy/postgresql
    tag: 17.6.0-debian-12-r4
  auth:
    username: ""
    password: ""
    database: postgres
